/* tslint:disable */
/* eslint-disable */
/**
 * Kiberon Labs Design Tokens API
 * OpenAPI compliant REST API built using tRPC
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface ErrorBADREQUESTIssuesInner
 */
export interface ErrorBADREQUESTIssuesInner {
    /**
     * 
     * @type {string}
     * @memberof ErrorBADREQUESTIssuesInner
     */
    message: string;
}

/**
 * Check if a given object implements the ErrorBADREQUESTIssuesInner interface.
 */
export function instanceOfErrorBADREQUESTIssuesInner(value: object): value is ErrorBADREQUESTIssuesInner {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ErrorBADREQUESTIssuesInnerFromJSON(json: any): ErrorBADREQUESTIssuesInner {
    return ErrorBADREQUESTIssuesInnerFromJSONTyped(json, false);
}

export function ErrorBADREQUESTIssuesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorBADREQUESTIssuesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function ErrorBADREQUESTIssuesInnerToJSON(json: any): ErrorBADREQUESTIssuesInner {
    return ErrorBADREQUESTIssuesInnerToJSONTyped(json, false);
}

export function ErrorBADREQUESTIssuesInnerToJSONTyped(value?: ErrorBADREQUESTIssuesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

