/* tslint:disable */
/* eslint-disable */
/**
 * Kiberon Labs Design Tokens API
 * OpenAPI compliant REST API built using tRPC
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { ErrorBADREQUESTIssuesInner } from './ErrorBADREQUESTIssuesInner.js';
import {
    ErrorBADREQUESTIssuesInnerFromJSON,
    ErrorBADREQUESTIssuesInnerFromJSONTyped,
    ErrorBADREQUESTIssuesInnerToJSON,
    ErrorBADREQUESTIssuesInnerToJSONTyped,
} from './ErrorBADREQUESTIssuesInner.js';

/**
 * The error information
 * @export
 * @interface ErrorNOTFOUND
 */
export interface ErrorNOTFOUND {
    /**
     * The error message
     * @type {string}
     * @memberof ErrorNOTFOUND
     */
    message: string;
    /**
     * The error code
     * @type {string}
     * @memberof ErrorNOTFOUND
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     * @type {Array<ErrorBADREQUESTIssuesInner>}
     * @memberof ErrorNOTFOUND
     */
    issues?: Array<ErrorBADREQUESTIssuesInner>;
}

/**
 * Check if a given object implements the ErrorNOTFOUND interface.
 */
export function instanceOfErrorNOTFOUND(value: object): value is ErrorNOTFOUND {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function ErrorNOTFOUNDFromJSON(json: any): ErrorNOTFOUND {
    return ErrorNOTFOUNDFromJSONTyped(json, false);
}

export function ErrorNOTFOUNDFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorNOTFOUND {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'code': json['code'],
        'issues': json['issues'] == null ? undefined : ((json['issues'] as Array<any>).map(ErrorBADREQUESTIssuesInnerFromJSON)),
    };
}

export function ErrorNOTFOUNDToJSON(json: any): ErrorNOTFOUND {
    return ErrorNOTFOUNDToJSONTyped(json, false);
}

export function ErrorNOTFOUNDToJSONTyped(value?: ErrorNOTFOUND | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'code': value['code'],
        'issues': value['issues'] == null ? undefined : ((value['issues'] as Array<any>).map(ErrorBADREQUESTIssuesInnerToJSON)),
    };
}

