/* tslint:disable */
/* eslint-disable */
/**
 * Kiberon Labs Design Tokens API
 * OpenAPI compliant REST API built using tRPC
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface PostHello200Response
 */
export interface PostHello200Response {
    /**
     * 
     * @type {string}
     * @memberof PostHello200Response
     */
    greeting: string;
}

/**
 * Check if a given object implements the PostHello200Response interface.
 */
export function instanceOfPostHello200Response(value: object): value is PostHello200Response {
    if (!('greeting' in value) || value['greeting'] === undefined) return false;
    return true;
}

export function PostHello200ResponseFromJSON(json: any): PostHello200Response {
    return PostHello200ResponseFromJSONTyped(json, false);
}

export function PostHello200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostHello200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'greeting': json['greeting'],
    };
}

export function PostHello200ResponseToJSON(json: any): PostHello200Response {
    return PostHello200ResponseToJSONTyped(json, false);
}

export function PostHello200ResponseToJSONTyped(value?: PostHello200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'greeting': value['greeting'],
    };
}

